import = ["/home/shiro/.config/alacritty/dracula.toml"]

[font]
size = 13.0

[font.bold]
family = "JetBrainsMono NerdFont"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono NerdFont"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono NerdFont"
style = "Italic"

[font.normal]
family = "JetBrainsMono NerdFont"
style = "Regular"

[mouse]
hide_when_typing = true

[window]
decorations = "none"
dynamic_padding = true
