#! /bin/sh

sxhkd &
picom &
polybar &

xsetroot -cursor_name left_ptr
bspc monitor -d term browser code media others

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config normal_border_color "#44475a"
bspc config active_border_color "#bd93f9"
bspc config focused_border_color "#ff79c6"
bspc config presel_feedback_color "#6272a4"

bspc rule -a Google-chrome desktop='^2'
bspc rule -a Code desktop='^3'

